export type RecommendationPriority = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
export type RecommendationStatus = "ACTIVE" | "EXPIRED" | "DISMISSED" | "COMPLETED";

export interface RecommendationReason {
  description: string;
}

/**
 * A recommendation generated by the AI Decision Engine.
 */
export interface Recommendation {
  id: string;
  title: string;
  summary?: string;
  action: string;
  priority: RecommendationPriority;
  confidence: number;
  explanation: RecommendationReason[];
  affectedEvents: string[]; // IDs of events that contributed to this recommendation
  status: RecommendationStatus;
  generatedAt: string; // ISO 8601
  expiresAt?: string; // ISO 8601
}
